global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2
  publish_frequency: 1
  static_map: true 
  resolution: 0.05
  width: 20
  height: 20
  
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}




